jx:
  imagePullSecrets:
  - tekton-container-registry-auth
  secrets:
    adminUser:
      password: todo
      username: todo
    hmacToken: todo
    pipelineUser:
      email: jenkins-x@googlegroups.com
      token: todo
      username: jenkins-x-labs-bot
jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
  environments:
  - key: dev
    owner: dbarroso
    repository: jx3-minikube
  - key: staging
  - key: production
  ingress:
    domain: 192.168.99.100.nip.io
    externalDNS: false
    namespaceSubDomain: -secret-infra.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: dbarroso
  repository: bucketrepo
  secretStorage: vault
  vault: {}
  webhook: lighthouse
jxRequirementsIngressExternalDNS:
  enabled: false
jxRequirementsIngressTLS:
  enabled: false
jxRequirementsVault:
  enabled: true
