apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: dbarroso
    provider: https://github.com
    providerKind: github
    repositories:
    - name: jx-minikube-test-project
    scheduler: in-repo
